### ISSUE TITLE
[FEAT]: Filter Servapps by updates available

### ISSUE THREAD

**Issue by tarbib** [azukaar/Cosmos-Server#91] opened 2023-09-14 13:31 UTC
### Feature Description

Hello,
I have some containers without auto updates and quite a lot of servapps currently.
I'd like to display Servapps with update available.
Thanks

**Comment by azukaar** [comment] 2023-09-15 08:09
yes this is good, I am planning to rework the servapp screen entirely to make it easier to manage your apps, this includes adding filters, changing order, etc...

**Comment by azukaar** [comment] 2024-03-29 16:59
Duplicate of #39

**Closed by azukaar** 2024-03-29 16:59 UTC
Labels: enhancement

**Comment by FlyingToto** [comment] 2024-07-30 18:09
Would it be possible to also add a log of containers which got updated tracking: 

- timestamp of the update
- from which image version to which image version.

also:

- keep the previous image version online for a few weeks
- provide a way to rollback to the previous version (and disable auto-update)
