### ISSUE TITLE
[FEAT]: Testing SMTP option

### ISSUE THREAD

**Issue by mzb2xeo** [azukaar/Cosmos-Server#260] opened 2024-05-28 04:58 UTC
### Feature Description

Testing the smtp config required me to scroll to the end of the page to save, then go to users, create new user, then send a invite, and then send password reset emails. 

Request the following be added within the "Emails - SMTP" section:
1. An additional save button 
2. A box to enter a test email address
3. A send/test button to execute.

**Comment by azukaar** [comment] 2024-05-30 07:29
Duplicate of #76

**Closed by azukaar** 2024-05-30 07:29 UTC
