### ISSUE TITLE
[FEAT]: Display Badge in Market for new applications

### ISSUE THREAD

**Issue by arvchristos** [azukaar/Cosmos-Server#231] opened 2024-04-02 11:00 UTC
### Feature Description

Thank you for the amazing implementation so far!

A good idea would be to have a badge for new applications added to the Market so that we can parse through new instead of featured ones (or satisfy our self-hosting addiction).

I am not sure whether this is easy as it should require a state (unless it is possible to fetch metadata from git or add a new field in the `index.json` metadata for each application with the date of introduction to the market).

**Comment by azukaar** [comment] 2024-04-02 11:26
Thank you! 
Duplicate of #125

**Closed by azukaar** 2024-04-02 11:26 UTC

**Comment by arvchristos** [comment] 2024-04-02 11:55
Oh my searching skills failed me. Thank you for the ultra fast response!
