### ISSUE TITLE
[FEAT]: Improving networks when creating a container

### ISSUE THREAD

**Issue by SSTentacleSS** [azukaar/Cosmos-Server#115] opened 2023-10-25 09:52 UTC
### Feature Description

A small change aimed at improving the naming of networks, when I want, for example, to create a new container - I expect that when specifying label

```env
cosmos-network-name: network-name
```

instead of AUTO, with this parameter set, it would be intuitively better if cosmos itself created a network with the name specified in cosmos-network-name, now cosmos ignores this parameter and writes a random network name there and uses a random network accordingly

**Comment by SSTentacleSS** [comment] 2023-10-25 09:58
Perhaps it makes sense to create a network in [ConnectToSecureNetwork](https://github.com/azukaar/Cosmos-Server/blob/8a5e261bd10959c072c478952479915672fd2d07/src/docker/network.go#L167-L169) instead of creating a random one

Or, for example, specify one additional label that will force cosmos-server to create this network

**Comment by azukaar** [comment] 2023-10-25 10:04
Cosmos does not ignore the parameter, it creates a new network when cosmos-network-name does not exist (as in you didn't create the network). If it does exist, it will follow the label
If you are trying to import a docker-compose and absolutely want the container network to have a specific name, you should create the network in the network part of the compose file

{
  "services": ...,
  "networks": [ 
     ... here
   ]
}  

Closing the ticket for now but feel free to continue the conversation

**Closed by azukaar** 2023-10-25 10:04 UTC

**Comment by SSTentacleSS** [comment] 2023-10-25 10:13
Creates a network, but with a random name, which is sometimes not quite what you would like and what you expect, especially when docker-compose is not used, but Market is used

> Cosmos does not ignore the parameter, it creates a new network when cosmos-network-name does not exist (as in you didn't create the network). If it does exist, it will follow the label If you are trying to import a docker-compose and absolutely want the container network to have a specific name, you should create the network in the network part of the compose file
> 
> { "services": ..., "networks": [ ... here ] }
> 
> Closing the ticket for now but feel free to continue the conversation

As I looked, it creates a network, but with a random name, which is sometimes not quite what you would like and what you expect, especially when docker-compose is not used, but Market is used

Yes, of course, you can create a network yourself with the specified name, but wouldn’t it be better to add an option so that cosmos creates a network that is not random, but specifically specified?

**Comment by azukaar** [comment] 2023-10-25 10:28
Sorry for the misunderstanding, I didn't mean to say you had to create the network **manually** but you do have to declare it in the compose file in order for it to exist.
For example like this:

https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Immich/cosmos-compose.json#L173

The randomized network when network does not exist is to prevent stopped network from connecting to newly created network (you can remove a network while having a stopped container connected to it. If you re-create the network, the old container will re-connect to it)

**Comment by SSTentacleSS** [comment] 2023-10-25 10:51
Hmm, okay, got you, thanks!

Then maybe it’s worth adding options for editing official compose files in Market? or is it possible to expand customization by adding the option to add/remove networks as in the compose file?

**Comment by azukaar** [comment] 2023-10-25 11:01
For the market it's different, as the wizard does not let you customize to this extent (you can customize more relevant stuff like env vars, volumes and binds).
Creating a new random network is the intended behaviour for the market
